### ISSUE TITLE
not matching values

### ISSUE THREAD

**Issue by breakthewall** [yvesago/borvo#1]
Hi Yves,

I tried to use Belenios-tool without success because of "missing public keys". Then, I found your tool and tried to check our results of a testing election. Unfortunately, I have the following error:

![Image 25-03-2021 à 10 24](https://user-images.githubusercontent.com/28150216/112450226-74b94400-8d54-11eb-8cf7-8df726f1af79.jpg)

Do you have any idea of what is going wrong?

Thank you for your help.

Best regards,
Joan

**Comment by yvesago** [comment]
Thx for the issue.
The good news  is that the homomorphic count is good.
The trouble is between partial decryption factors or discrete log compute.
This need more investigations ....

**Comment by yvesago** [comment]
I forget to manage partial decryption factors with many trustees 
fixed in #v0.2.2

**Comment by breakthewall** [comment]
It works!
Thanks
Joan
